# Generated by Django 3.2.15 on 2023-08-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('attend', models.IntegerField()),
                ('people_count', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
