# Generated by Django 3.2.15 on 2023-08-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rvsp', '0004_rename_telephone_confirmacao_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmacao',
            old_name='phone',
            new_name='telephone',
        ),
    ]
