# Generated by Django 3.2.15 on 2023-08-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rvsp', '0005_rename_phone_confirmacao_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmacao',
            old_name='telephone',
            new_name='phone',
        ),
    ]
